SELECT 
    COD_ESTABELECIMENTO,
    COD_DEPOSITO,
    DEPOSITO,
    DATA,
    FAMILIA_COMERCIAL,
    COD_ITEM,
    DESC_ITEM,
    QTD,
    PESO,
    CUSTO_FINANCEIRO,
    CASE    
        WHEN QTD > 0 THEN 'ENTRADA'
        WHEN QTD < 0 THEN 'SAÍDA'
        ELSE 'VERIFICAR'
    END AS MOVIMENTACAO,
    TIPO_OPERACAO,
    DESC_TIPO_OPERACAO
FROM 
    VW_AUDIT_RM_GERENCIAMENTO_ESTOQUE
WHERE 
    COD_ESTABELECIMENTO = 'R241'
    AND DATA BETWEEN '2025-07-01' AND '2025-12-31'
    AND TIPO_OPERACAO IN ('1.5.005', '1.5.020', '1.7.008', '2.5.005', '2.7.008')
