SELECT
    FAT.COD_ESTABELECIMENTO,
    FAT.DATA_NOTA_FISCAL,
    FAT.NUM_NOTA_FISCAL,
    CASE 
        WHEN FAT.SISTEMA = 'AX' THEN KDX.[SERIE+NF]
        ELSE NULL 
    END AS SERIE_NF_AX,
    FAT.CRIAR_BIN,
    FAT.CFOP,
    FAT.DESC_TIPO_OPERACAO,
    COUNT(FAT.COD_ITEM) AS QTD_ITENS,
    SUM(ISNULL(FAT.VALOR, 0)) AS VALOR_TOTAL,
    CASE 
        WHEN FAT.SISTEMA = 'AX' THEN SUM(ISNULL(KDX.CUSTO_FINANCEIRO, 0)) OVER (PARTITION BY FAT.COD_ESTABELECIMENTO, FAT.DATA_NOTA_FISCAL, KDX.[SERIE+NF])
        ELSE SUM(ISNULL(KDX.CUSTO_FINANCEIRO, 0)) OVER (PARTITION BY FAT.COD_ESTABELECIMENTO, FAT.DATA_NOTA_FISCAL, FAT.NUM_NOTA_FISCAL)
    END AS CUSTO_FINANCEIRO_TOTAL,    
    CASE 
        WHEN FAT.SISTEMA = 'AX' THEN SUM(ISNULL(KDX.PESO, 0)) OVER (PARTITION BY FAT.COD_ESTABELECIMENTO, FAT.DATA_NOTA_FISCAL, KDX.[SERIE+NF])
        ELSE SUM(ISNULL(KDX.PESO, 0)) OVER (PARTITION BY FAT.COD_ESTABELECIMENTO, FAT.DATA_NOTA_FISCAL, FAT.NUM_NOTA_FISCAL)
    END AS PESO_TOTAL,
    CASE
        WHEN FAT.CRIAR_BIN = 'Não' THEN 
            CASE 
                WHEN FAT.SISTEMA = 'AX' THEN SUM(ISNULL(KDX.PESO, 0)) OVER (PARTITION BY FAT.COD_ESTABELECIMENTO, FAT.DATA_NOTA_FISCAL, KDX.[SERIE+NF]) * 5.41
                ELSE SUM(ISNULL(KDX.PESO, 0)) OVER (PARTITION BY FAT.COD_ESTABELECIMENTO, FAT.DATA_NOTA_FISCAL, FAT.NUM_NOTA_FISCAL) * 5.41
            END
        WHEN FAT.CRIAR_BIN = 'Sim' THEN 0
        ELSE 0
    END AS VALOR_APROX,
    ROUND(SUM(ISNULL(FAT.VALOR, 0)) * 0.0308, 2) AS APROX_IMPOSTO,
    FAT.SISTEMA	
FROM
    VW_AUDIT_RM_ORDENS_VENDA AS FAT
LEFT JOIN
    VW_AUDIT_RM_GERENCIAMENTO_ESTOQUE AS KDX 
ON 
    FAT.COD_ESTABELECIMENTO = KDX.COD_ESTABELECIMENTO
    AND FAT.COD_ITEM = KDX.COD_ITEM
    AND FAT.NUM_NOTA_FISCAL = KDX.NUM_NOTA_FISCAL
    AND FAT.DESC_TIPO_OPERACAO = KDX.DESC_TIPO_OPERACAO
    AND FAT.SISTEMA = KDX.SISTEMA
WHERE
    FAT.COD_ESTABELECIMENTO = 'R761'
    AND FAT.DATA_NOTA_FISCAL BETWEEN '2024-07-01' AND '2025-07-01'
    AND FAT.CFOP IN ('5.102', '5.405', '6.102', '6.404')
    AND FAT.NUM_NOTA_FISCAL NOT LIKE 'NFeS%'
    AND FAT.NUM_NOTA_FISCAL NOT LIKE '%EST'
GROUP BY
    FAT.COD_ESTABELECIMENTO,
    FAT.DATA_NOTA_FISCAL,
    FAT.NUM_NOTA_FISCAL,
    FAT.CRIAR_BIN,
    FAT.CFOP,
    FAT.DESC_TIPO_OPERACAO,
    FAT.SISTEMA,
    KDX.[SERIE+NF],  -- Coluna com colchetes
    KDX.CUSTO_FINANCEIRO,
    KDX.PESO;
