SELECT 
    COD_ESTABELECIMENTO,
    COD_CLIENTE,
    NOME_CLIENTE,
    -- Se tiver conglomerado, agrupa por ele, senão agrupa pelo nome do cliente
    COALESCE(CONGLOMERADO, NOME_CLIENTE) AS GRUPO_AGRUPAMENTO,
    CONGLOMERADO,
    [CPF/CNPJ],
    SUM(VALOR) AS VALOR_TOTAL
FROM    
    VW_AUDIT_RM_ORDENS_VENDA
WHERE
    COD_ESTABELECIMENTO = 'R121'
    AND DATA_NOTA_FISCAL BETWEEN '2025-07-01' AND '2025-12-31'
    AND DESC_TIPO_OPERACAO LIKE '%BONIFICACAO%'
GROUP BY    
    COD_ESTABELECIMENTO,
    COD_CLIENTE,
    NOME_CLIENTE,
    COALESCE(CONGLOMERADO, NOME_CLIENTE),
    CONGLOMERADO,
    [CPF/CNPJ]
ORDER BY
    COALESCE(CONGLOMERADO, NOME_CLIENTE),
    NOME_CLIENTE,
    SUM(VALOR) ASC;
        )
) AS BASE
GROUP BY GRUPO, COD_ESTABELECIMENTO, PESSOA
ORDER BY GRUPO, PERCENTUAL_BONIFICACAO_ESTABELECIMENTO DESC;
