SELECT
    COD_ESTABELECIMENTO,
    DATA_TRANSACAO,
    COMPROVANTE,
    CASE    
        WHEN VALOR > 0 THEN 'DÉBITO'
        WHEN VALOR < 0 THEN 'CRÉDITO'
        ELSE 'VERIFICAR'
    END AS DEB_CRED,
    TEXTO_TRANSACAO,
    CONTA_CONTABIL,
    NOME_CONTA,
    VALOR
FROM    
    VW_AUDIT_RM_TRANSACOES_CONTA_CONTABIL
WHERE   
    COD_ESTABELECIMENTO = 'R241'
    AND DATA_TRANSACAO BETWEEN '2025-01-01' AND '2025-12-31'
    AND CONTA_CONTABIL = '1.1.01.01.003'
    AND VALOR > 1000; 
