SELECT  
    COD_ESTABELECIMENTO,
    YEAR(DATA_TRANSACAO) AS ANO,
    MONTH(DATA_TRANSACAO) AS MES,
    CASE
        WHEN MONTH(DATA_TRANSACAO) = 1 THEN 'JANEIRO'
        WHEN MONTH(DATA_TRANSACAO) = 2 THEN 'FEVEREIRO'
        WHEN MONTH(DATA_TRANSACAO) = 3 THEN 'MARÇO'
        WHEN MONTH(DATA_TRANSACAO) = 4 THEN 'ABRIL'
        WHEN MONTH(DATA_TRANSACAO) = 5 THEN 'MAIO'
        WHEN MONTH(DATA_TRANSACAO) = 6 THEN 'JUNHO'
        WHEN MONTH(DATA_TRANSACAO) = 7 THEN 'JULHO'
        WHEN MONTH(DATA_TRANSACAO) = 8 THEN 'AGOSTO'
        WHEN MONTH(DATA_TRANSACAO) = 9 THEN 'SETEMBRO'
        WHEN MONTH(DATA_TRANSACAO) = 10 THEN 'OUTUBRO'
        WHEN MONTH(DATA_TRANSACAO) = 11 THEN 'NOVEMBRO'
        WHEN MONTH(DATA_TRANSACAO) = 12 THEN 'DEZEMBRO'
        ELSE 'VERIFICAR'
    END AS NOME_MES,
    CONTA_CONTABIL,
    NOME_CONTA,
    SUM(CASE WHEN VALOR_MOEDA > 0 THEN VALOR_MOEDA ELSE 0 END) AS TOTAL_DEBITO_MENSAL,
    COUNT(CASE WHEN VALOR_MOEDA > 0 THEN 1 END) AS TOTAL_TRANSACOES_DEBITO,
    SUM(CASE WHEN VALOR_MOEDA < 0 THEN VALOR_MOEDA ELSE 0 END) AS TOTAL_CREDITO_MENSAL,
    COUNT(CASE WHEN VALOR_MOEDA < 0 THEN 1 END) AS TOTAL_TRANSACOES_CREDITO,
    SUM(VALOR_MOEDA) AS TOTAL_LIQUIDO_MENSAL
FROM
    VW_AUDIT_RM_TRANSACOES_CONTA_CONTABIL
WHERE   
    COD_ESTABELECIMENTO = 'R111'
    AND DATA_TRANSACAO BETWEEN '2025-07-01' AND '2025-12-31' -- Data Base
    AND CONTA_CONTABIL = '1.1.01.01.003'
GROUP BY
    COD_ESTABELECIMENTO,
    YEAR(DATA_TRANSACAO),
    MONTH(DATA_TRANSACAO),
    CONTA_CONTABIL,
    NOME_CONTA
HAVING
    SUM(CASE WHEN VALOR_MOEDA > 0 THEN VALOR_MOEDA ELSE 0 END) > 20000 
ORDER BY
    ANO, 
    MES
