SELECT
    COD_ESTABELECIMENTO,
    COD_CLIENTE,
    NOME_CLIENTE,
    YEAR(DATA_TRANSACAO) AS ANO,
    MONTH(DATA_TRANSACAO) AS MES,
    CASE
        WHEN MONTH(DATA_TRANSACAO) = 1 THEN 'JANEIRO'
        WHEN MONTH(DATA_TRANSACAO) = 2 THEN 'FEVEREIRO'
        WHEN MONTH(DATA_TRANSACAO) = 3 THEN 'MARCO'
        WHEN MONTH(DATA_TRANSACAO) = 4 THEN 'ABRIL'
        WHEN MONTH(DATA_TRANSACAO) = 5 THEN 'MAIO'
        WHEN MONTH(DATA_TRANSACAO) = 6 THEN 'JUNHO'
        WHEN MONTH(DATA_TRANSACAO) = 7 THEN 'JULHO'
        WHEN MONTH(DATA_TRANSACAO) = 8 THEN 'AGOSTO'
        WHEN MONTH(DATA_TRANSACAO) = 9 THEN 'SETEMBRO'
        WHEN MONTH(DATA_TRANSACAO) = 10 THEN 'OUTUBRO'
        WHEN MONTH(DATA_TRANSACAO) = 11 THEN 'NOVEMBRO'
        WHEN MONTH(DATA_TRANSACAO) = 12 THEN 'DEZEMBRO'
        ELSE 'VERIFICAR'
    END AS NOM_MES,
    SUM(VALOR_PARCELA) AS TOTAL_VALOR_MENSAL,
    COUNT(*) AS TOTAL_TRANSACOES
FROM
    VW_AUDIT_RM_TRANSACOES_FECHADAS
WHERE
    COD_ESTABELECIMENTO IN ('R351', 'R352') -- Alterar para o distribuidor que irá ser auditado!!!
    AND DATA_TRANSACAO BETWEEN '2025-07-01' AND '2025-12-31' -- Alterar para o escopo que será auditado!!!
    AND METODO_PAGAMENTO LIKE '%REC_CXA%'
GROUP BY
    COD_ESTABELECIMENTO,
    COD_CLIENTE,
    NOME_CLIENTE,
    YEAR(DATA_TRANSACAO),
    MONTH(DATA_TRANSACAO),
    CASE
        WHEN MONTH(DATA_TRANSACAO) = 1 THEN 'JANEIRO'
        WHEN MONTH(DATA_TRANSACAO) = 2 THEN 'FEVEREIRO'
        WHEN MONTH(DATA_TRANSACAO) = 3 THEN 'MARCO'
        WHEN MONTH(DATA_TRANSACAO) = 4 THEN 'ABRIL'
        WHEN MONTH(DATA_TRANSACAO) = 5 THEN 'MAIO'
        WHEN MONTH(DATA_TRANSACAO) = 6 THEN 'JUNHO'
        WHEN MONTH(DATA_TRANSACAO) = 7 THEN 'JULHO'
        WHEN MONTH(DATA_TRANSACAO) = 8 THEN 'AGOSTO'
        WHEN MONTH(DATA_TRANSACAO) = 9 THEN 'SETEMBRO'
        WHEN MONTH(DATA_TRANSACAO) = 10 THEN 'OUTUBRO'
        WHEN MONTH(DATA_TRANSACAO) = 11 THEN 'NOVEMBRO'
        WHEN MONTH(DATA_TRANSACAO) = 12 THEN 'DEZEMBRO'
        ELSE 'VERIFICAR'
    END
HAVING
    SUM(VALOR_PARCELA) > 20000
ORDER BY
    COD_ESTABELECIMENTO,
    COD_CLIENTE,
    ANO DESC,
    MES DESC;
