SELECT
    COD_ESTABELECIMENTO,
    COD_FORNECEDOR,
    NOME_FORNECEDOR,
    DATA_TRANSACAO,
    DATA_VENCIMENTO,
    GETDATE() AS DATA_HOJE,
    DATEDIFF(DAY, DATA_VENCIMENTO, GETDATE()) AS DIAS,
    CASE
        WHEN DATEDIFF(DAY, DATA_VENCIMENTO, GETDATE()) <= 30 THEN 'A VENCER'
        WHEN DATEDIFF(DAY, DATA_VENCIMENTO, GETDATE()) > 30 AND DATEDIFF(DAY, DATA_VENCIMENTO, GETDATE()) <= 60 THEN 'VENCIDOS ATÉ 60 DIAS'
        WHEN DATEDIFF(DAY, DATA_VENCIMENTO, GETDATE()) > 60 AND DATEDIFF(DAY, DATA_VENCIMENTO, GETDATE()) <= 90 THEN 'VENCIDOS ATÉ 90 DIAS'
        WHEN DATEDIFF(DAY, DATA_VENCIMENTO, GETDATE()) > 90 AND DATEDIFF(DAY, DATA_VENCIMENTO, GETDATE()) <= 120 THEN 'VENCIDOS ATÉ 120 DIAS'
        WHEN DATEDIFF(DAY, DATA_VENCIMENTO, GETDATE()) > 120 AND DATEDIFF(DAY, DATA_VENCIMENTO, GETDATE()) <= 180 THEN 'VENCIDOS ATÉ 180 DIAS'
        WHEN DATEDIFF(DAY, DATA_VENCIMENTO, GETDATE()) > 180 AND DATEDIFF(DAY, DATA_VENCIMENTO, GETDATE()) <= 360 THEN 'VENCIDOS ATÉ 360 DIAS'
        WHEN DATEDIFF(DAY, DATA_VENCIMENTO, GETDATE()) > 360 THEN 'VENCIDOS A MAIS DE 360 DIAS'
        ELSE 'VERIFICAR'
    END AS AGING_LIST,
    PERFIL_LANC,
    VALOR_MOEDA,
    STATUS
FROM 
    VW_AUDIT_RM_TRANSACOES_FORNECEDOR 
WHERE
    COD_ESTABELECIMENTO IN ('R351', 'R352') -- ALTERAR PARA O DISTRIBUIDOR QUE SERÁ AUDITADO!!!
    AND PERFIL_LANC IN ('DPS', 'DFS')
    AND DATEDIFF(DAY, DATA_VENCIMENTO, GETDATE()) > 30
ORDER BY
    COD_FORNECEDOR;
