DECLARE @DATA_BASE DATE = '2025-12-31';

SELECT
    COD_ESTABELECIMENTO,
    COD_FORNECEDOR,
    NOME_FORNECEDOR,
    DATA_TRANSACAO,
    DATA_VENCIMENTO,
    DATA_LIQUIDACAO,
    GETDATE() AS DATA_HOJE,
    DATEDIFF(DAY, DATA_VENCIMENTO, @DATA_BASE) AS DIAS,
    CASE
        WHEN DATEDIFF(DAY, DATA_VENCIMENTO, @DATA_BASE) > 0 AND DATEDIFF(DAY, DATA_VENCIMENTO, @DATA_BASE) <= 30 THEN 'VENCIDOS ATÉ 30 DIAS'
        WHEN DATEDIFF(DAY, DATA_VENCIMENTO, @DATA_BASE) > 30 AND DATEDIFF(DAY, DATA_VENCIMENTO, @DATA_BASE) <= 60 THEN 'VENCIDOS ATÉ 60 DIAS'
        WHEN DATEDIFF(DAY, DATA_VENCIMENTO, @DATA_BASE) > 60 AND DATEDIFF(DAY, DATA_VENCIMENTO, @DATA_BASE) <= 90 THEN 'VENCIDOS ATÉ 90 DIAS'
        WHEN DATEDIFF(DAY, DATA_VENCIMENTO, @DATA_BASE) > 90 AND DATEDIFF(DAY, DATA_VENCIMENTO, @DATA_BASE) <= 120 THEN 'VENCIDOS ATÉ 120 DIAS'
        WHEN DATEDIFF(DAY, DATA_VENCIMENTO, @DATA_BASE) > 120 AND DATEDIFF(DAY, DATA_VENCIMENTO, @DATA_BASE) <= 180 THEN 'VENCIDOS ATÉ 180 DIAS'
        WHEN DATEDIFF(DAY, DATA_VENCIMENTO, @DATA_BASE) > 180 AND DATEDIFF(DAY, DATA_VENCIMENTO, @DATA_BASE) <= 360 THEN 'VENCIDOS ATÉ 360 DIAS'
        WHEN DATEDIFF(DAY, DATA_VENCIMENTO, @DATA_BASE) > 360 THEN 'VENCIDOS A MAIS DE 360 DIAS'
        ELSE 'VERIFICAR'
    END AS AGING_LIST,
    PERFIL_LANC,
    VALOR_MOEDA,
    STATUS
FROM 
    VW_AUDIT_RM_TRANSACOES_FORNECEDOR 
WHERE
    COD_ESTABELECIMENTO IN ('R351', 'R352')
    AND PERFIL_LANC IN ('DPS', 'DFS')
    AND DATA_TRANSACAO <= '2025-12-31'
    AND (DATA_LIQUIDACAO >= '2025-01-01' OR DATA_LIQUIDACAO = '1900-01-01')
    AND DATEDIFF(DAY, DATA_VENCIMENTO, @DATA_BASE) > 30
ORDER BY
    COD_FORNECEDOR
