SELECT
    COD_ESTABELECIMENTO,
    COD_CLIENTE,
    NOME_CLIENTE,
    DATA_TRANSACAO,
    DATA_VENCIMENTO,
    DATA_LIQUIDACAO,
    DATEDIFF(DAY, DATA_VENCIMENTO, GETDATE()) AS DIAS_ATRASO,
    CASE
        WHEN DATEDIFF(DAY, DATA_VENCIMENTO, GETDATE()) <= 30 THEN 'VENCIDOS ATÉ 30 DIAS'
        WHEN DATEDIFF(DAY, DATA_VENCIMENTO, GETDATE()) > 30 AND DATEDIFF(DAY, DATA_VENCIMENTO, GETDATE()) <= 60 THEN 'VENCIDOS ATÉ 60 DIAS'
        WHEN DATEDIFF(DAY, DATA_VENCIMENTO, GETDATE()) > 60 AND DATEDIFF(DAY, DATA_VENCIMENTO, GETDATE()) <= 90 THEN 'VENCIDOS ATÉ 90 DIAS'
        WHEN DATEDIFF(DAY, DATA_VENCIMENTO, GETDATE()) > 90 AND DATEDIFF(DAY, DATA_VENCIMENTO, GETDATE()) <= 120 THEN 'VENCIDOS ATÉ 120 DIAS'
        WHEN DATEDIFF(DAY, DATA_VENCIMENTO, GETDATE()) > 120 AND DATEDIFF(DAY, DATA_VENCIMENTO, GETDATE()) <= 180 THEN 'VENCIDOS ATÉ 180 DIAS'
        WHEN DATEDIFF(DAY, DATA_VENCIMENTO, GETDATE()) > 180 AND DATEDIFF(DAY, DATA_VENCIMENTO, GETDATE()) <= 360 THEN 'VENCIDOS ATÉ 360 DIAS'
        WHEN DATEDIFF(DAY, DATA_VENCIMENTO, GETDATE()) > 360 AND DATEDIFF(DAY, DATA_VENCIMENTO, GETDATE()) <= 720 THEN 'VENCIDOS ATÉ 720 DIAS'
        WHEN DATEDIFF(DAY, DATA_VENCIMENTO, GETDATE()) > 720 THEN 'VENCIDOS A MAIS DE 720 DIAS'
        ELSE 'SEM VENCIMENTO'
    END AS CATEGORIA_ATRASO,
    PERFIL_LANC,
    NUM_NOTA_FISCAL,
    VALOR_MOEDA,
    STATUS
FROM    
    VW_AUDIT_RM_TRANSACOES_CLIENTES
WHERE   
   COD_ESTABELECIMENTO = 'R351' 
   AND PERFIL_LANC NOT IN ('TCC', 'CCR')
   AND DATA_TRANSACAO BETWEEN '2025-01-12' AND '2025-12-31' -- Data Base
   AND (DATA_LIQUIDACAO >= '2025-01-01' OR DATA_LIQUIDACAO = '1900-01-01') -- Puxa apenas os abertos
GROUP BY
    COD_ESTABELECIMENTO,
    COD_CLIENTE,
    NOME_CLIENTE,
    DATA_TRANSACAO,
    DATA_VENCIMENTO,
    DATA_LIQUIDACAO,
    PERFIL_LANC,
    NUM_NOTA_FISCAL,
    VALOR_MOEDA,
    STATUS
HAVING
    DATEDIFF(DAY, DATA_VENCIMENTO, GETDATE()) > 720;
