SELECT
    COD_ESTABELECIMENTO,
    COD_FORNECEDOR,
    NOME_FORNECEDOR,
    [CNPJ/CPF],
    DATA_TRANSACAO,
    DATA_VENCIMENTO,
    GETDATE() AS DATA_HOJE,
    CASE
        WHEN DATA_VENCIMENTO >= GETDATE() THEN 0 
        ELSE DATEDIFF(DAY, DATA_VENCIMENTO, GETDATE())  
    END AS DIAS_ATRASO,
    CASE
        WHEN DATEDIFF(DAY, DATA_VENCIMENTO, GETDATE()) BETWEEN 0 AND 30 THEN 'VENCIDOS ATÉ 30 DIAS'
        WHEN DATEDIFF(DAY, DATA_VENCIMENTO, GETDATE()) BETWEEN 31 AND 60 THEN 'VENCIDOS ATÉ 60 DIAS'
        WHEN DATEDIFF(DAY, DATA_VENCIMENTO, GETDATE()) BETWEEN 61 AND 90 THEN 'VENCIDOS ATÉ 90 DIAS'
        WHEN DATEDIFF(DAY, DATA_VENCIMENTO, GETDATE()) BETWEEN 91 AND 120 THEN 'VENCIDOS ATÉ 120 DIAS'
        WHEN DATEDIFF(DAY, DATA_VENCIMENTO, GETDATE()) BETWEEN 121 AND 180 THEN 'VENCIDOS ATÉ 180 DIAS'
        WHEN DATEDIFF(DAY, DATA_VENCIMENTO, GETDATE()) BETWEEN 181 AND 360 THEN 'VENCIDOS ATÉ 360 DIAS'
        WHEN DATEDIFF(DAY, DATA_VENCIMENTO, GETDATE()) > 360 THEN 'VENCIDOS A MAIS DE 360 DIAS'
        ELSE 'SEM VENCIMENTO'
    END AS CATEGORIA_ATRASO,
    PERFIL_LANC,
    NUM_NOTA_FISCAL,
    VALOR_MOEDA
FROM    
    VW_AUDIT_RM_TRANSACOES_FORNECEDOR
WHERE
    COD_ESTABELECIMENTO IN ('R241', 'R243')
    AND PERFIL_LANC = 'AVI'
    AND DATA_TRANSACAO BETWEEN '2025-07-01' AND '2025-12-31' -- Data base
    AND STATUS = 'ABERTO'
ORDER BY
    COD_FORNECEDOR,
    NUM_NOTA_FISCAL
