SELECT
    COD_ESTABELECIMENTO,
    COD_CLIENTE,
    NOME_CLIENTE,
    DATA_TRANSACAO,
    DATA_VENCIMENTO,
    DATEDIFF(DAY, GETDATE(), DATA_VENCIMENTO) AS DIF_DATA,
    CASE
        WHEN DATEDIFF(DAY, GETDATE(), DATA_VENCIMENTO) <= 30 THEN 'No Prazo'
        WHEN DATEDIFF(DAY, GETDATE(), DATA_VENCIMENTO) BETWEEN 61 AND 90 THEN 'Venc. 61 a 90'
        WHEN DATEDIFF(DAY, GETDATE(), DATA_VENCIMENTO) BETWEEN 91 AND 120 THEN 'Venc. 91 a 120'
        WHEN DATEDIFF(DAY, GETDATE(), DATA_VENCIMENTO) > 120 THEN 'Venc. Mais 120'
        ELSE 'Verificar'
    END AS 'Aging_List',
    SUM(CASE WHEN PERFIL_LANCAMENTO = 'ACL' THEN VALOR_PARCELA ELSE 0 END) AS 'VALOR_ACL',
    SUM(CASE WHEN PERFIL_LANCAMENTO = 'DPC' THEN VALOR_PARCELA ELSE 0 END) AS 'VALOR_DPC',
    SUM(CASE WHEN PERFIL_LANCAMENTO = 'ATC' THEN VALOR_PARCELA ELSE 0 END) AS 'VALOR_ATC',
    SUM(CASE WHEN PERFIL_LANCAMENTO = 'TCC' THEN VALOR_PARCELA ELSE 0 END) AS 'VALOR_TCC',
    (SUM(CASE WHEN PERFIL_LANCAMENTO = 'ACL' THEN VALOR_PARCELA ELSE 0 END) - 
     SUM(CASE WHEN PERFIL_LANCAMENTO = 'DPC' THEN VALOR_PARCELA ELSE 0 END)) AS 'DIF_ACL_DPC',
    (SUM(CASE WHEN PERFIL_LANCAMENTO = 'ATC' THEN VALOR_PARCELA ELSE 0 END) -
     SUM(CASE WHEN PERFIL_LANCAMENTO = 'TCC' THEN VALOR_PARCELA ELSE 0 END)) AS 'DIF_ATC_TCC',
    
    CASE 
        WHEN SUM(CASE WHEN PERFIL_LANCAMENTO = 'DPC' THEN VALOR_PARCELA ELSE 0 END) > 
             SUM(CASE WHEN PERFIL_LANCAMENTO = 'ATC' THEN VALOR_PARCELA ELSE 0 END) 
        THEN 'Baixar ATC'
        WHEN SUM(CASE WHEN PERFIL_LANCAMENTO = 'DPC' THEN VALOR_PARCELA ELSE 0 END) < 
             SUM(CASE WHEN PERFIL_LANCAMENTO = 'ATC' THEN VALOR_PARCELA ELSE 0 END) 
        THEN 'Baixar DPC'
        ELSE 'Valores Iguais'
    END AS 'STATUS'
    
FROM    
    VW_AUDIT_RM_TRANSACOES_FECHADAS 
WHERE   
    COD_ESTABELECIMENTO IN ('R351', 'R352')
    AND DATEDIFF(DAY, GETDATE(), DATA_VENCIMENTO) >= 61
GROUP BY
    COD_ESTABELECIMENTO,
    COD_CLIENTE,
    NOME_CLIENTE,
    DATA_TRANSACAO,
    DATA_VENCIMENTO
ORDER BY 
    DATA_VENCIMENTO;
