SELECT
    COD_ESTABELECIMENTO,
    COD_CLIENTE,
    NOME_CLIENTE,
    DATA_TRANSACAO,
    DATA_VENCIMENTO,
    DATEDIFF(DAY, GETDATE(), DATA_VENCIMENTO) AS DIF_DATA,
    CASE
        WHEN DATEDIFF(DAY, GETDATE(), DATA_VENCIMENTO) > 0 
            AND DATEDIFF(DAY, GETDATE(), DATA_VENCIMENTO) <= 30 THEN 'Venc. até 30 dias'
        WHEN DATEDIFF(DAY, GETDATE(), DATA_VENCIMENTO) BETWEEN 31 AND 60 THEN 'Venc. 31 a 60'
        WHEN DATEDIFF(DAY, GETDATE(), DATA_VENCIMENTO) BETWEEN 61 AND 90 THEN 'Venc. 61 a 90'
        WHEN DATEDIFF(DAY, GETDATE(), DATA_VENCIMENTO) BETWEEN 91 AND 120 THEN 'Venc. 91 a 120'
        WHEN DATEDIFF(DAY, GETDATE(), DATA_VENCIMENTO) > 120 THEN 'Venc. Mais 120'
        ELSE 'Verificar'
    END AS 'Aging_List',
    SUM(CASE WHEN PERFIL_LANC = 'ACL' THEN VALOR_MOEDA ELSE 0 END) AS 'VALOR_ACL',
    SUM(CASE WHEN PERFIL_LANC = 'DPC' THEN VALOR_MOEDA ELSE 0 END) AS 'VALOR_DPC',
    (SUM(CASE WHEN PERFIL_LANC = 'ACL' THEN VALOR_MOEDA ELSE 0 END) - 
     SUM(CASE WHEN PERFIL_LANC = 'DPC' THEN VALOR_MOEDA ELSE 0 END)) AS 'DIF_ACL_DPC',

    SUM(CASE WHEN PERFIL_LANC = 'ATC' THEN VALOR_MOEDA ELSE 0 END) AS 'VALOR_ATC',
    SUM(CASE WHEN PERFIL_LANC = 'TCC' THEN VALOR_MOEDA ELSE 0 END) AS 'VALOR_TCC',
    (SUM(CASE WHEN PERFIL_LANC = 'ATC' THEN VALOR_MOEDA ELSE 0 END) -
     SUM(CASE WHEN PERFIL_LANC = 'TCC' THEN VALOR_MOEDA ELSE 0 END)) AS 'DIF_ATC_TCC',

    CASE 
        -- Primeiro verifica se o valor total do ACL é zero
        WHEN SUM(CASE WHEN PERFIL_LANC = 'ACL' THEN VALOR_MOEDA ELSE 0 END) = 0 
        THEN 'OK'
        -- Se ACL não for zero e DPC for maior que ACL
        WHEN SUM(CASE WHEN PERFIL_LANC = 'DPC' THEN VALOR_MOEDA ELSE 0 END) > 
             SUM(CASE WHEN PERFIL_LANC = 'ACL' THEN VALOR_MOEDA ELSE 0 END) 
        THEN 'Baixar ACL'
        -- Se ACL não for zero e for menor que DPC
        WHEN SUM(CASE WHEN PERFIL_LANC = 'DPC' THEN VALOR_MOEDA ELSE 0 END) < 
             SUM(CASE WHEN PERFIL_LANC = 'ACL' THEN VALOR_MOEDA ELSE 0 END) 
        THEN 'Baixar DPC'

        -- Se ATC não for zero e TCC for maior que ATC
        WHEN SUM(CASE WHEN PERFIL_LANC = 'TCC' THEN VALOR_MOEDA ELSE 0 END) >
             SUM(CASE WHEN PERFIL_LANC = 'ATC' THEN VALOR_MOEDA ELSE 0 END)
        THEN 'Baixar ATC'
        -- Se ATC não for zero e for menor que TCC
        WHEN SUM(CASE WHEN PERFIL_LANC = 'TCC' THEN VALOR_MOEDA ELSE 0 END) <
             SUM(CASE WHEN PERFIL_LANC = 'ATC' THEN VALOR_MOEDA ELSE 0 END)
        THEN 'Baixar TCC'
        ELSE 'Não Aplicável'

    END AS 'STATUS'
FROM    
    VW_AUDIT_RM_TRANSACOES_CLIENTES
WHERE   
    COD_ESTABELECIMENTO = 'R241' -- Inserir os Distribuidores que serão auditados
    AND DATA_TRANSACAO BETWEEN '2025-07-01' AND '2025-12-31' -- Inserir a Data Base da Auditoria
GROUP BY
    COD_ESTABELECIMENTO,
    COD_CLIENTE,
    NOME_CLIENTE,
    DATA_TRANSACAO,
    DATA_VENCIMENTO
HAVING
    SUM(CASE WHEN PERFIL_LANC = 'ACL' THEN VALOR_MOEDA ELSE 0 END) <> 0 -- Retorna os casos diferentes de zero 
ORDER BY 
    DATA_VENCIMENTO;
