WITH AdiantamentosACL AS (
    SELECT
        TF.COD_ESTABELECIMENTO,
        TF.COD_CLIENTE,
        TF.NOME_CLIENTE,
        REPLACE(REPLACE(REPLACE(REPLACE(OV.[CPF/CNPJ], '.', ''), '-', ''), '/', ''), ' ', '') AS CPF_CNPJ_LIMPO,
        LEN(REPLACE(REPLACE(REPLACE(REPLACE(OV.[CPF/CNPJ], '.', ''), '-', ''), '/', ''), ' ', '')) AS CARACTERES,
        TF.PERFIL_LANCAMENTO,
        TF.DATA_VENCIMENTO,
        TF.DATA_TRANSACAO,
        GETDATE() AS DATA_HOJE,
        DATEDIFF(DAY, TF.DATA_VENCIMENTO, GETDATE()) AS DIAS,
        CASE    
            WHEN TF.DATA_VENCIMENTO >= GETDATE() THEN 'A VENCER'
            WHEN DATEDIFF(DAY, TF.DATA_VENCIMENTO, GETDATE()) BETWEEN 1 AND 30 THEN 'VENCIDOS ATÉ 30 DIAS'
            WHEN DATEDIFF(DAY, TF.DATA_VENCIMENTO, GETDATE()) BETWEEN 31 AND 60 THEN 'VENCIDOS ATÉ 60 DIAS'
            WHEN DATEDIFF(DAY, TF.DATA_VENCIMENTO, GETDATE()) BETWEEN 61 AND 90 THEN 'VENCIDOS ATÉ 90 DIAS'
            WHEN DATEDIFF(DAY, TF.DATA_VENCIMENTO, GETDATE()) BETWEEN 91 AND 120 THEN 'VENCIDOS ATÉ 120 DIAS'
            WHEN DATEDIFF(DAY, TF.DATA_VENCIMENTO, GETDATE()) BETWEEN 121 AND 180 THEN 'VENCIDOS ATÉ 180 DIAS'
            WHEN DATEDIFF(DAY, TF.DATA_VENCIMENTO, GETDATE()) > 180 THEN 'VENCIDOS MAIS DE 180 DIAS'
            ELSE 'SEM VENCIMENTO'
        END AS CATEGORIA_ATRASO,
        TF.VALOR_TITULO,
        COUNT(*) OVER (PARTITION BY TF.COD_CLIENTE) AS QTD_ADIANTAMENTOS,
        ROW_NUMBER() OVER (
            PARTITION BY TF.COD_CLIENTE 
            ORDER BY TF.DATA_TRANSACAO DESC, TF.DATA_VENCIMENTO DESC
        ) AS NUM_ADIANTAMENTO
    FROM
        VW_AUDIT_RM_TRANSACOES_FECHADAS AS TF
    LEFT JOIN
        VW_AUDIT_RM_ORDENS_VENDA AS OV 
        ON TF.COD_ESTABELECIMENTO = OV.COD_ESTABELECIMENTO
        AND TF.COD_CLIENTE = OV.COD_CLIENTE 
    WHERE
        TF.COD_ESTABELECIMENTO IN ('R351', 'R352') -- ALTERAR PARA O DISTRIBUIDOR QUE SERÁ AUDITADO!!!
        AND TF.DATA_TRANSACAO BETWEEN '2025-07-01' AND '2025-12-31' -- ALTERAR PARA O ESCOPO QUE SERÁ AUDITADO!!!
        AND TF.PERFIL_LANCAMENTO = 'ACL'
)
SELECT
    COD_ESTABELECIMENTO,
    COD_CLIENTE,
    NOME_CLIENTE,
    PERFIL_LANCAMENTO,
    DATA_VENCIMENTO,
    DATA_TRANSACAO,
    DATA_HOJE,
    DIAS,
    CATEGORIA_ATRASO,
    VALOR_TITULO,
    QTD_ADIANTAMENTOS,
    NUM_ADIANTAMENTO,
    SUM(VALOR_TITULO) OVER (PARTITION BY COD_CLIENTE) AS VALOR_TOTAL_ADIANTAMENTOS,
    CASE 
        WHEN QTD_ADIANTAMENTOS = 1 THEN 'Único Adiantamento'
        WHEN QTD_ADIANTAMENTOS = 2 THEN 'Dois Adiantamentos'
        WHEN QTD_ADIANTAMENTOS = 3 THEN 'Três Adiantamentos'
        ELSE 'Múltiplos Adiantamentos (' + CAST(QTD_ADIANTAMENTOS AS VARCHAR(10)) + ')'
    END AS STATUS_ADIANTAMENTOS,
    CPF_CNPJ_LIMPO,
    CARACTERES
FROM
    AdiantamentosACL
WHERE
    -- Filtro para CPF (11 caracteres) - usando coluna já calculada
    CARACTERES = 11
    -- Filtro para múltiplos adiantamentos
    AND QTD_ADIANTAMENTOS > 1
ORDER BY
    QTD_ADIANTAMENTOS DESC,
    COD_CLIENTE,
    DATA_TRANSACAO DESC;
