WITH DadosBase AS (
    SELECT
        COD_ESTABELECIMENTO,
        COD_FORNECEDOR,
        NOME_FORNECEDOR,
        [CNPJ/CPF],
        -- Calculando o CNPJ/CPF limpo (sem pontuação) e a quantidade de caracteres
        REPLACE(REPLACE(REPLACE(REPLACE([CNPJ/CPF], '.', ''), '-', ''), '/', ''), ' ', '') AS CNPJ_CPF_LIMPO,
        LEN(REPLACE(REPLACE(REPLACE(REPLACE([CNPJ/CPF], '.', ''), '-', ''), '/', ''), ' ', '')) AS QTD_CARACTERES,
        DATA_TRANSACAO,
        DATA_VENCIMENTO,
        PERFIL_LANC,
        NUM_NOTA_FISCAL,
        VALOR_MOEDA,
        CASE
            WHEN DATA_VENCIMENTO >= GETDATE() THEN 0 
            ELSE DATEDIFF(DAY, DATA_VENCIMENTO, GETDATE())  
        END AS DIAS_ATRASO,
        CASE
            WHEN DATEDIFF(DAY, DATA_VENCIMENTO, GETDATE()) BETWEEN 0 AND 30 THEN 'VENCIDOS ATÉ 30 DIAS'
            WHEN DATEDIFF(DAY, DATA_VENCIMENTO, GETDATE()) BETWEEN 31 AND 60 THEN 'VENCIDOS ATÉ 60 DIAS'
            WHEN DATEDIFF(DAY, DATA_VENCIMENTO, GETDATE()) BETWEEN 61 AND 90 THEN 'VENCIDOS ATÉ 90 DIAS'
            WHEN DATEDIFF(DAY, DATA_VENCIMENTO, GETDATE()) BETWEEN 91 AND 120 THEN 'VENCIDOS ATÉ 120 DIAS'
            WHEN DATEDIFF(DAY, DATA_VENCIMENTO, GETDATE()) BETWEEN 121 AND 180 THEN 'VENCIDOS ATÉ 180 DIAS'
            WHEN DATEDIFF(DAY, DATA_VENCIMENTO, GETDATE()) BETWEEN 181 AND 360 THEN 'VENCIDOS ATÉ 360 DIAS'
            WHEN DATEDIFF(DAY, DATA_VENCIMENTO, GETDATE()) > 360 THEN 'VENCIDOS A MAIS DE 360 DIAS'
            ELSE 'SEM VENCIMENTO'
        END AS CATEGORIA_ATRASO
    FROM    
        VW_AUDIT_RM_TRANSACOES_FORNECEDOR
    WHERE
        COD_ESTABELECIMENTO IN ('R241', 'R243')
        AND PERFIL_LANC = 'AVI'
        AND DATA_TRANSACAO BETWEEN '2025-10-01' AND '2025-12-31'
        AND STATUS = 'ABERTO'
        AND LEN(REPLACE(REPLACE(REPLACE(REPLACE([CNPJ/CPF], '.', ''), '-', ''), '/', ''), ' ', '')) = '11'
)
SELECT
    COD_ESTABELECIMENTO,
    COD_FORNECEDOR,
    NOME_FORNECEDOR,
    [CNPJ/CPF],
    CNPJ_CPF_LIMPO,
    QTD_CARACTERES,
    CASE
        WHEN QTD_CARACTERES = 11 THEN 'CPF'
        WHEN QTD_CARACTERES = 14 THEN 'CNPJ'
        ELSE 'TAMANHO INVÁLIDO'
    END AS TIPO_DOCUMENTO,
    DATA_TRANSACAO,
    DATA_VENCIMENTO,
    GETDATE() AS DATA_HOJE,
    DIAS_ATRASO,
    CATEGORIA_ATRASO,
    PERFIL_LANC,
    NUM_NOTA_FISCAL,
    SUM(VALOR_MOEDA) AS VALOR_TOTAL
FROM 
    DadosBase
GROUP BY    
    COD_ESTABELECIMENTO,
    COD_FORNECEDOR,
    NOME_FORNECEDOR,
    [CNPJ/CPF],
    CNPJ_CPF_LIMPO,
    QTD_CARACTERES,
    DATA_TRANSACAO,
    DATA_VENCIMENTO,
    DIAS_ATRASO,
    CATEGORIA_ATRASO,
    PERFIL_LANC,
    NUM_NOTA_FISCAL
ORDER BY
    COD_FORNECEDOR,
    NUM_NOTA_FISCAL;
