SELECT
    COD_ESTABELECIMENTO,
    COD_CLIENTE,
    NOME_CLIENTE,
    DATA_TRANSACAO,
    DATA_VENCIMENTO,
    GETDATE() AS DATA_HOJE,
    CASE
        WHEN DATA_VENCIMENTO >= GETDATE() THEN 0  -- Ainda não venceu
        ELSE DATEDIFF(DAY, DATA_VENCIMENTO, GETDATE())  -- Já venceu
    END AS DIAS_ATRASO,
    CASE
        WHEN DATA_VENCIMENTO >= GETDATE() THEN 'A VENCER'
        WHEN DATEDIFF(DAY, DATA_VENCIMENTO, GETDATE()) BETWEEN 0 AND 30 THEN 'VENCIDOS ATÉ 30 DIAS'
        WHEN DATEDIFF(DAY, DATA_VENCIMENTO, GETDATE()) BETWEEN 31 AND 60 THEN 'VENCIDOS ATÉ 60 DIAS'
        WHEN DATEDIFF(DAY, DATA_VENCIMENTO, GETDATE()) BETWEEN 61 AND 90 THEN 'VENCIDOS ATÉ 90 DIAS'
        WHEN DATEDIFF(DAY, DATA_VENCIMENTO, GETDATE()) BETWEEN 91 AND 120 THEN 'VENCIDOS ATÉ 120 DIAS'
        WHEN DATEDIFF(DAY, DATA_VENCIMENTO, GETDATE()) BETWEEN 121 AND 180 THEN 'VENCIDOS ATÉ 180 DIAS'
        WHEN DATEDIFF(DAY, DATA_VENCIMENTO, GETDATE()) BETWEEN 181 AND 360 THEN 'VENCIDOS ATÉ 360 DIAS'
        WHEN DATEDIFF(DAY, DATA_VENCIMENTO, GETDATE()) > 360 THEN 'VENCIDOS A MAIS DE 360 DIAS'
        ELSE 'SEM VENCIMENTO'
    END AS CATEGORIA_ATRASO,
    PERFIL_LANCAMENTO,
    NOTA_FISCAL,
    VALOR_PARCELA
FROM    
    VW_AUDIT_RM_TRANSACOES_FECHADAS
WHERE
    COD_ESTABELECIMENTO IN ('R351', 'R352') -- ALTERAR PARA O DISTRIBUIDOR QUE SERÁ AUDITADO!!!
    AND PERFIL_LANCAMENTO = 'AVI'
ORDER BY
    COD_CLIENTE,
    NOTA_FISCAL;
