SELECT 
    COD_ESTABELECIMENTO,
    COD_CLIENTE,
    NOME_CLIENTE,
    DATA_TRANSACAO,
    DATA_VENCIMENTO,
    DATA_LIQUIDACAO,
    NUM_NOTA_FISCAL,
    COMPROVANTE,
    PESO_BIN_ORIGINAL,
    PESO_BIN_BAIXADO,
    PESO_BIN_ABERTO,
    VALOR,
    STATUS,
    DIAS_ATRASO
FROM 
    VW_AUDIT_RM_ABERTO_BIN
WHERE 
    COD_ESTABELECIMENTO = 'R351'
    AND DIAS_ATRASO > 360
    AND PESO_BIN_ABERTO > 200
    AND DATA_TRANSACAO <= '2025-12-31'  -- DATA BASE
    AND STATUS = 'ABERTO'
    AND SISTEMA = 'D365'
    AND (
        DATA_LIQUIDACAO > '2025-12-31' 
        OR DATA_LIQUIDACAO = '1900-01-01'
        OR DATA_LIQUIDACAO IS NULL
    )
ORDER BY    
    COD_CLIENTE;
