SELECT
    TF.COD_ESTABELECIMENTO,
    TF.COD_FORNECEDOR,
    TF.NOME_FORNECEDOR,
    REPLACE(REPLACE(REPLACE(REPLACE(TF.[CNPJ/CPF], '.', ''), '-', ''), '/', ''), ' ', '') AS CPF_CNPJ_LIMPO,
    LEN(REPLACE(REPLACE(REPLACE(REPLACE(TF.[CNPJ/CPF], '.', ''), '-', ''), '/', ''), ' ', '')) AS CARACTERES,
    TF.PERFIL_LANC,
    TF.DATA_VENCIMENTO,
    TF.DATA_TRANSACAO,
    GETDATE() AS DATA_HOJE, -- A data de Hoje é a Data Base, devemos alterar conforme cronograma da Auditoria
    DATEDIFF(DAY, TF.DATA_VENCIMENTO, GETDATE()) AS DIAS,
    CASE    
        WHEN TF.DATA_VENCIMENTO >= GETDATE() THEN 'A VENCER'
        WHEN DATEDIFF(DAY, TF.DATA_VENCIMENTO, GETDATE()) BETWEEN 1 AND 30 THEN 'VENCIDOS ATÉ 30 DIAS'
        WHEN DATEDIFF(DAY, TF.DATA_VENCIMENTO, GETDATE()) BETWEEN 31 AND 60 THEN 'VENCIDOS ATÉ 60 DIAS'
        WHEN DATEDIFF(DAY, TF.DATA_VENCIMENTO, GETDATE()) BETWEEN 61 AND 90 THEN 'VENCIDOS ATÉ 90 DIAS'
        WHEN DATEDIFF(DAY, TF.DATA_VENCIMENTO, GETDATE()) BETWEEN 91 AND 120 THEN 'VENCIDOS ATÉ 120 DIAS'
        WHEN DATEDIFF(DAY, TF.DATA_VENCIMENTO, GETDATE()) BETWEEN 121 AND 180 THEN 'VENCIDOS ATÉ 180 DIAS'
        WHEN DATEDIFF(DAY, TF.DATA_VENCIMENTO, GETDATE()) > 180 THEN 'VENCIDOS MAIS DE 180 DIAS'
        ELSE 'SEM VENCIMENTO'
    END AS CATEGORIA_ATRASO,
    TF.VALOR_MOEDA,
    TF.STATUS,
    COUNT(*) OVER (PARTITION BY TF.COD_FORNECEDOR) AS QTD_ADIANTAMENTOS,
    ROW_NUMBER() OVER (
        PARTITION BY TF.COD_FORNECEDOR 
        ORDER BY TF.DATA_TRANSACAO DESC, TF.DATA_VENCIMENTO DESC
    ) AS NUM_ADIANTAMENTO
FROM
    VW_AUDIT_RM_TRANSACOES_FORNECEDOR AS TF  
WHERE
    TF.COD_ESTABELECIMENTO = 'R111' 
    AND TF.DATA_TRANSACAO BETWEEN '2025-07-01' AND '2025-12-31'
    AND TF.PERFIL_LANC = 'AFO'
    AND TF.STATUS = 'ABERTO'
    AND TF.VALOR_MOEDA > 0
    AND DATEDIFF(DAY, TF.DATA_VENCIMENTO, GETDATE()) > 30
    AND REPLACE(REPLACE(REPLACE(REPLACE(TF.[CNPJ/CPF], '.', ''), '-', ''), '/', ''), ' ', '') = '11'
