SELECT
    COD_ESTABELECIMENTO,
    COD_FORNECEDOR,
    NOME_FORNECEDOR,
    [CNPJ/CPF],
    -- Calculando o CNPJ/CPF limpo (sem pontuação) e a quantidade de caracteres
    REPLACE(REPLACE(REPLACE(REPLACE([CNPJ/CPF], '.', ''), '-', ''), '/', ''), ' ', '') AS CNPJ_CPF_LIMPO,
    LEN(REPLACE(REPLACE(REPLACE(REPLACE([CNPJ/CPF], '.', ''), '-', ''), '/', ''), ' ', '')) AS QTD_CARACTERES,
    DATA_TRANSACAO,
    DATA_VENCIMENTO,
    PERFIL_LANC,
    NUM_NOTA_FISCAL,
    VALOR_MOEDA,
    -- Conta quantos adiantamentos cada fornecedor tem
    COUNT(*) OVER (PARTITION BY COD_FORNECEDOR) AS QTD_ADIANTAMENTOS_FORNECEDOR
FROM    
    VW_AUDIT_RM_TRANSACOES_FORNECEDOR
WHERE
    COD_ESTABELECIMENTO = 'R111'
    AND PERFIL_LANC = 'AFO'
    AND DATA_TRANSACAO BETWEEN '2025-01-01' AND '2025-12-31'
    AND STATUS = 'ABERTO'
    AND LEN(REPLACE(REPLACE(REPLACE(REPLACE([CNPJ/CPF], '.', ''), '-', ''), '/', ''), ' ', '')) = 11  
GROUP BY    
    COD_ESTABELECIMENTO,
    COD_FORNECEDOR,
    NOME_FORNECEDOR,
    [CNPJ/CPF],
    REPLACE(REPLACE(REPLACE(REPLACE([CNPJ/CPF], '.', ''), '-', ''), '/', ''), ' ', ''),
    LEN(REPLACE(REPLACE(REPLACE(REPLACE([CNPJ/CPF], '.', ''), '-', ''), '/', ''), ' ', '')),
    DATA_TRANSACAO,
    DATA_VENCIMENTO,
    PERFIL_LANC,
    NUM_NOTA_FISCAL,
    VALOR_MOEDA
HAVING 
    COUNT(*) OVER (PARTITION BY COD_FORNECEDOR) > '11'
