SELECT
    COD_ESTABELECIMENTO,
    COD_CLIENTE,
    NOME_CLIENTE,
    MAX(DATA_TRANSACAO) AS DATA_TRANSACAO,
    MAX(DATA_VENCIMENTO) AS DATA_VENCIMENTO,
    GETDATE() AS DATA_HOJE,
    DATEDIFF(DAY, MAX(DATA_VENCIMENTO), GETDATE()) AS DIAS_ATRASO,
    CASE
        WHEN DATEDIFF(DAY, MAX(DATA_VENCIMENTO), GETDATE()) <= 30 THEN 'A VENCER'
        WHEN DATEDIFF(DAY, MAX(DATA_VENCIMENTO), GETDATE()) BETWEEN 31 AND 60 THEN 'VENCIDOS ATÉ 60 DIAS'
        WHEN DATEDIFF(DAY, MAX(DATA_VENCIMENTO), GETDATE()) BETWEEN 61 AND 90 THEN 'VENCIDOS ATÉ 90 DIAS'
        WHEN DATEDIFF(DAY, MAX(DATA_VENCIMENTO), GETDATE()) BETWEEN 91 AND 120 THEN 'VENCIDOS ATÉ 120 DIAS'
        WHEN DATEDIFF(DAY, MAX(DATA_VENCIMENTO), GETDATE()) BETWEEN 121 AND 180 THEN 'VENCIDOS ATÉ 180 DIAS'
        WHEN DATEDIFF(DAY, MAX(DATA_VENCIMENTO), GETDATE()) BETWEEN 181 AND 360 THEN 'VENCIDOS ATÉ 360 DIAS'
        WHEN DATEDIFF(DAY, MAX(DATA_VENCIMENTO), GETDATE()) BETWEEN 361 AND 720 THEN 'VENCIDOS ATÉ 720 DIAS'
        WHEN DATEDIFF(DAY, MAX(DATA_VENCIMENTO), GETDATE()) > 720 THEN 'VENCIDOS A MAIS DE 720 DIAS'
        ELSE 'SEM VENCIMENTO'
    END AS CATEGORIA_ATRASO,
    PERFIL_LANCAMENTO,
    NOTA_FISCAL,
    SUM(VALOR_PARCELA) AS VALOR_PARCELA_TOTAL
FROM
    VW_AUDIT_RM_TRANSACOES_FECHADAS
WHERE
    COD_ESTABELECIMENTO IN ('R351', 'R352') -- ALTERAR PARA O DISTRIBUIDOR QUE SERÁ AUDITADO!!!
    AND PERFIL_LANCAMENTO NOT IN ('TCC', 'CCR')
    AND DATEDIFF(DAY, DATA_VENCIMENTO, GETDATE()) > 720
GROUP BY
    COD_ESTABELECIMENTO,
    COD_CLIENTE,
    NOME_CLIENTE,
    PERFIL_LANCAMENTO,
    NOTA_FISCAL
ORDER BY
    COD_CLIENTE,
    NOTA_FISCAL;
