DECLARE @DATA_BASE DATE = '2025-12-31' -- Data Base

SELECT
    COD_FORNECEDOR,
    MAX(NOME_FORNECEDOR) AS NOME_FORNECEDOR,
    MAX(PERFIL_LANC) AS PERFIL_LANC,
    -- Soma condicional para o status 'ABERTO'
    SUM(CASE WHEN STATUS = 'ABERTO' THEN VALOR_MOEDA ELSE 0 END) AS VALOR_ABERTO,
    -- Soma condicional para outros status 'FECHADO' 
    SUM(CASE WHEN STATUS = 'FECHADO' THEN VALOR_MOEDA ELSE 0 END) AS VALOR_FECHADO,
    -- Soma valor geral
    SUM(VALOR_MOEDA) AS VALOR_TOTAL,
    -- Contagem por status
    SUM(CASE WHEN STATUS = 'ABERTO' THEN 1 ELSE 0 END) AS QTD_ABERTO,
    SUM(CASE WHEN STATUS = 'FECHADO' THEN 1 ELSE 0 END) AS QTD_FECHADO,
    -- Quantidade Total
    (SUM(CASE WHEN STATUS = 'ABERTO' THEN 1 ELSE 0 END)) + (SUM(CASE WHEN STATUS = 'FECHADO' THEN 1 ELSE 0 END)) AS QTD_TOTAL
FROM
    VW_AUDIT_RM_TRANSACOES_FORNECEDOR
WHERE
    COD_ESTABELECIMENTO IN ('R351', 'R352') -- Alterar para os Distribuidores que serão auditados
    AND DATA_TRANSACAO <= @DATA_BASE
    AND (DATA_LIQUIDACAO >= DATEADD(DAY, 1, @DATA_BASE) OR DATA_LIQUIDACAO = '1900-01-01')
    AND PERFIL_LANC = 'AFO'
    AND STATUS IN ('ABERTO', 'FECHADO') -- Filtro baseado nos status usados nas somas
GROUP BY
    COD_FORNECEDOR
HAVING
    SUM(VALOR_MOEDA) <> 0
ORDER BY
    SUM(CASE WHEN STATUS = 'ABERTO' THEN VALOR_MOEDA ELSE 0 END) DESC
