-- Data Base
DECLARE @DATA_BASE DATE = '2025-12-31' 

SELECT
    f.COD_ESTABELECIMENTO,
    f.COD_FORNECEDOR,
    f.NOME_FORNECEDOR,
    f.PERFIL_LANC,
    f.STATUS,
    -- Valor por fornecedor
    SUM(f.VALOR_MOEDA) AS VALOR_ADTO,
    -- Quantidade por fornecedor 
    COUNT(*) AS QTD_ADTO,
    -- Valor total do estabelecimento 
    SUM(SUM(f.VALOR_MOEDA)) OVER (PARTITION BY f.COD_ESTABELECIMENTO) AS VALOR_TOTAL_ADTO_ESTAB,
    -- Cálculo da frequência por VALOR (percentual do valor total)
    ROUND((SUM(f.VALOR_MOEDA) * 100.0 / 
           SUM(SUM(f.VALOR_MOEDA)) OVER (PARTITION BY f.COD_ESTABELECIMENTO)), 2) 
        AS FREQUENCIA_VALOR_PERCENTUAL
FROM
    VW_AUDIT_RM_TRANSACOES_FORNECEDOR f
WHERE
    f.COD_ESTABELECIMENTO IN ('R351', 'R352') -- Alterar para o Distribuidor que será auditado
    AND f.DATA_TRANSACAO <= @DATA_BASE
    AND (f.DATA_LIQUIDACAO >= DATEADD(DAY, 1, @DATA_BASE) OR f.DATA_LIQUIDACAO = '1900-01-01')
    AND f.PERFIL_LANC = 'AFO' -- Adiantamentos a Fornecedores
    AND f.STATUS = 'ABERTO'
GROUP BY    
    f.COD_ESTABELECIMENTO,
    f.COD_FORNECEDOR,
    f.NOME_FORNECEDOR,
    f.PERFIL_LANC,
    f.STATUS
ORDER BY
    f.COD_ESTABELECIMENTO,
    SUM(f.VALOR_MOEDA) DESC,  
    f.COD_FORNECEDOR ASC
    f.STATUS
ORDER BY
    f.COD_ESTABELECIMENTO,
    SUM(f.VALOR_MOEDA) DESC,  
    f.COD_FORNECEDOR ASC
