SELECT
    COD_ESTABELECIMENTO,
    COD_FORNECEDOR,
    NOME_FORNECEDOR,
    SUM(VALOR_MOEDA) AS TOTAL_VALOR,
    COUNT(*) AS TOTAL_REGISTROS_AFO
FROM
    VW_AUDIT_RM_TRANSACOES_FORNECEDOR
WHERE
    COD_ESTABELECIMENTO IN ('R351', 'R352') -- Alterar para o Distribuidor que está sendo auditado
    AND PERFIL_LANC = 'AFO'
    AND STATUS = 'ABERTO'
GROUP BY
    COD_ESTABELECIMENTO,
    COD_FORNECEDOR,
    NOME_FORNECEDOR
ORDER BY
    COUNT(*) DESC
