DECLARE @DATA_BASE DATE = '2025-12-31' -- Data Base

SELECT
    COD_ESTABELECIMENTO,
    COD_FORNECEDOR,
    NOME_FORNECEDOR,
    DATA_TRANSACAO,
    DATA_VENCIMENTO,
    DATA_LIQUIDACAO,
    GETDATE() AS DATA_HOJE,
    DATEDIFF(DAY, DATA_VENCIMENTO, @DATA_BASE) AS DIAS,
    PERFIL_LANC,
    VALOR_MOEDA,
    STATUS
FROM
    VW_AUDIT_RM_TRANSACOES_FORNECEDOR
WHERE
    COD_ESTABELECIMENTO IN ('R351', 'R352') -- Inserir os Distribuidores a serem auditados
    AND DATA_TRANSACAO <= @DATA_BASE
    AND (DATA_LIQUIDACAO >= '2026-01-01' OR DATA_LIQUIDACAO = '1900-01-01')
    AND PERFIL_LANC = 'AFO'
    AND STATUS = 'ABERTO'
    AND DATEDIFF(DAY, DATA_VENCIMENTO, @DATA_BASE) > 30
ORDER BY
    COD_FORNECEDOR ASC

