SELECT
    COD_ESTABELECIMENTO,
    COD_FORNECEDOR,
    NOME_FORNECEDOR,
    DATA_TRANSACAO,
    DATA_VENCIMENTO,
    GETDATE() AS DATA_HOJE,
    DATEDIFF(DAY, DATA_VENCIMENTO, GETDATE()) AS DIAS,
    PERFIL_LANC,
    VALOR_MOEDA,
    STATUS
FROM
    VW_AUDIT_RM_TRANSACOES_FORNECEDOR
WHERE
    COD_ESTABELECIMENTO IN ('R351', 'R352') -- Alterar para os Distribuidores que serão auditados!
    AND PERFIL_LANC = 'AFO'
    AND STATUS = 'ABERTO'
    AND DATEDIFF(DAY, DATA_VENCIMENTO, GETDATE()) > 30

